# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  build:
    desc: Build yaml-compose binary
    cmds:
      - go build -o yaml-compose ./main.go

  test:
    desc: Run unit tests
    cmds:
      - go test ./...

  install:
    desc: Install yaml-compose
    deps:
      - build
    cmds:
      - go install .

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
